// frontend/src/components/Book.tsx
import {
    type menuItem,
    handleBookDelete,
    editShelvesOfBook,
    getShelvesOfBook,
    getAllShelves
} from '../dbDataHandler';
import {useRef, useState} from "react";
import { KebabMenu } from "./KebabMenu";
import { useAppContext} from "./App";
import {toast} from "react-toastify";

export interface BookProps {
    title: string;
    author: string;
    publish_year: string;
    isbn: string;
    isbn_h: string;
    img_url: string;
}

export interface BooksWithShelves extends BookProps {
    shelf: string;
}

export default function Book({ title, author, publish_year, isbn, isbn_h, img_url }: BookProps) {
    const { reload } = useAppContext();
    const [isDeleted, setIsDeleted] = useState(false);
    const [allShelves, setAllShelves] = useState<string[]>([]);
    const [shelves, setShelves] = useState<string[]>([]);
    const dialogRef = useRef<HTMLDialogElement>(null);

    const menuItems: menuItem[] = [
        {label: 'Delete', onClick: () => {
            handleBookDelete(title, isbn)
                setIsDeleted(true);
        }},
        {label: 'Edit shelves', onClick: () => editShelves()},
    ];

    async function editShelves(): Promise<void> {
        const AllShelves: string[] = await getAllShelves();
        const shelves: string[] = await getShelvesOfBook(isbn);
        setAllShelves(AllShelves);
        setShelves(shelves);
        dialogRef.current?.showModal();
    }

    function handleShelfChange(shelfName: string, isChecked: boolean): void {
        if (isChecked) {
            setShelves(prev => prev.includes(shelfName) ? prev : [...prev, shelfName]);
        } else {
            setShelves(prev => prev.filter(s => s !== shelfName));
        }
    }

    async function handleSave(): Promise<void> {
        try {
            await editShelvesOfBook(isbn, shelves);
            dialogRef.current?.close();
            reload();
        } catch (e) {
            toast.error('Error saving shelves');
            console.error('Error saving shelves:', e);
        }
    }

    return (
        <div className={isDeleted ? 'book deleted': 'book'}>
            <img src={img_url} alt={`${title} by ${author}`}/>
            <div className={'book_content'}
                id={title.toLowerCase()
                    .replace(/ /g, '')}
            >
                <p title={title} className={'title'}>{title}</p>
                <div className={'meta'}>
                    <p className={'author'}>{author}</p>
                    <p className={'publishDate'}>Year: {publish_year}</p>
                    <p className={'isbn'}>{isbn_h}</p>
                </div>
                <KebabMenu
                    items={menuItems}
                />
            </div>
            <dialog ref={dialogRef}>
                <div>
                    <h3>Edit shelves for "{title}"</h3>
                    <div style={{ margin: '15px 0' }}>
                        {(allShelves).map((shelfName: string) => (
                            <div key={shelfName} style={{ marginBottom: '10px' }}>
                                <label>
                                    <input
                                        type={'checkbox'}
                                        checked={shelves.includes(shelfName)}
                                        onChange={(e) => handleShelfChange(shelfName, e.target.checked)}
                                    />
                                    {shelfName}
                                </label>
                            </div>
                        ))}
                    </div>
                    <button onClick={handleSave}>
                        Close
                    </button>
                </div>
            </dialog>
        </div>
    );
}

// frontend/src/app/components/book/book.component.ts
import {Component, ElementRef, inject, Input, signal, ViewChild} from '@angular/core';
import {Book} from '../../models/book.type';
import {NgOptimizedImage} from '@angular/common';
import {KebabMenuComponent, MenuItem} from '../kebab-menu/kebab-menu.component';
import {BookService} from '../../services/book.service';
import {ShelfService} from '../../services/shelf.service';

import {MatCheckboxModule} from '@angular/material/checkbox';
import {MatButtonModule} from '@angular/material/button';

@Component({
  selector: 'app-book',
  imports: [
    NgOptimizedImage,
    KebabMenuComponent,
    MatCheckboxModule,
    MatButtonModule
  ],
  template: `
    <div class="book">
      <img
        ngSrc="{{ book.img_url }}"
        priority="high"
        height="640"
        width="400"
        alt="\`{{ book.title }} by {{ book.author }}\`"
      />
      <div class="book_content">
        <p class="title">{{ book.title }}</p>
        <div class="meta">
          <p class="author">{{ book.author }}</p>
          <p class="publishYear">{{ book.publish_year }}</p>
          <p class="isbn">{{ book.isbn_h }}</p>
        </div>
        <app-kebab-menu
          [items]="menuItems"
        />
      </div>
      <dialog #shelfSelection class="shelf_dialog">
        <div class="dialog_content">
          <h3>Edit shelves for "{{ book.title }}"</h3>
          <div class="dialog_body">
            @for (shelf of shelfService.shelfNames(); track shelf) {
              <div style="margin-bottom: 10px">
                <mat-checkbox
                  [checked]="shelves().includes(shelf)"
                  (change)="handleShelfChange(shelf, $event.checked)"
                >
                  {{ shelf }}
                </mat-checkbox>
              </div>
            }
          </div>
          <div class="button-container">
            <button mat-flat-button color="primary" (click)="handleSave()">
              Close
            </button>
          </div>
        </div>
      </dialog>
    </div>
  `,
  styleUrl: './book.component.scss',
})
export class BookComponent {
  @Input() book!: Book;
  @ViewChild('shelfSelection') dialog!: ElementRef<HTMLDialogElement>;
  bookService = inject(BookService);
  shelfService = inject(ShelfService);
  shelves = signal<string[]>([]);

  openShelfSelection() {
    const shelfData = this.shelfService.shelvedBooks()
      .filter(b => b.isbn === this.book.isbn)
      .map(b => b.shelf);
    this.shelves.set(shelfData);
    this.dialog.nativeElement.showModal();
  }

  handleShelfChange(shelf: string, isChecked: boolean) {
    if (isChecked) {
      if (!this.shelves().includes(shelf)) this.shelves.set([...this.shelves(), shelf]);
    } else {
      this.shelves.set(this.shelves().filter(s => s !== shelf));
    }
  }

  handleSave() {
    this.shelfService.editShelvesOfBook(this.book.isbn, this.shelves())
      .subscribe({
        next: () => {
          this.shelfService.getShelvedBooks();
          this.shelfService.getSidebarData();
          this.dialog.nativeElement.close();
        },
        error: (err) => {
          console.error('Failed to save shelves', err);
        }
      });
  }

  handleBookDelete() {
    this.bookService
      .deleteBook(this.book.title, this.book.isbn)?.subscribe({
      next: () => {
        this.bookService.getBooks();
        console.log(`Book deleted`);
      },
      error: (err) => {
        console.error('Failed to delete book', err);
      }
    })
  }

  menuItems: MenuItem[] = [
    {label: 'Delete', action: () => {this.handleBookDelete()}},
    {label: 'Edit shelves', action: () => {this.openShelfSelection()}}
  ]
}
